import { playSfx } from '../engine/sfx.js';
import { resolveGameDifficulty, getGameChoiceCount } from '../../core/game-difficulty-policy.js';

export class BalloonPopGame {
  constructor(containerId,audioEngine,onComplete,onBack){this.container=document.getElementById(containerId);this.audio=audioEngine;this.onComplete=onComplete;this.onBack=onBack;this.level=1;this.ageId='2-3y';this.score=0;this.targetNumber=1;this.finished=false;this.attempts=0;}
  start(level=this.level,options={}){this.ageId=options.ageId||'2-3y';this.difficulty=resolveGameDifficulty(this.ageId,level,options);this.level=this.difficulty.level;this.score=0;this.attempts=0;this.finished=false;this.renderShell();this.spawnRound();}
  renderShell(){this.container.innerHTML=`<div class="w-full max-w-2xl h-full min-h-[520px] flex flex-col my-auto relative overflow-hidden"><div class="game-bar z-10 p-2"><button id="btn-back-balloon" class="game-back" aria-label="Voltar">⬅️</button><h2 class="game-title">🎈 Balões</h2><div class="game-dots" id="balloon-dots">${Array.from({length:this.difficulty.rounds},()=>'<span></span>').join('')}</div><span class="sr-only"><span id="balloon-score">0</span>/${this.difficulty.rounds}</span></div><div class="text-center bg-white/80 rounded-3xl px-4 py-3 shadow mx-2"><p class="text-sm text-slate-600">Estoure o número</p><span id="target-num" class="text-4xl font-black text-indigo-600">?</span></div><div id="sky-area" class="flex-1 relative w-full min-h-[360px] overflow-hidden"></div></div>`;document.getElementById('btn-back-balloon').addEventListener('click',()=>this.onBack());}
  spawnRound(){if(this.score>=this.difficulty.rounds)return this.finish();const max=Math.max(3,this.level+2);this.targetNumber=Math.floor(Math.random()*max)+1;const targetEl=document.getElementById('target-num');if(targetEl)targetEl.textContent=this.targetNumber;const sky=document.getElementById('sky-area');if(!sky)return;sky.innerHTML='';const nums=new Set([this.targetNumber]);const count=getGameChoiceCount(this.difficulty,2,1,5);while(nums.size<count)nums.add(Math.floor(Math.random()*max)+1);const colors=['#fb7185','#38bdf8','#34d399','#fbbf24','#a78bfa'];const slots=Array.from({length:nums.size},(_,i)=>((i+.5)/nums.size)*100);this.audio.prompt(null,`Estoure o número ${this.targetNumber}`);[...nums].sort(()=>Math.random()-0.5).forEach((n,i)=>{const balloon=document.createElement('button');balloon.className='absolute w-20 h-24 rounded-[50%] shadow-xl flex items-center justify-center text-3xl font-black text-white transition-transform touch-target';balloon.style.left=`calc(${slots[i]}% - 40px)`;balloon.style.top=`${20+Math.random()*55}%`;balloon.style.backgroundColor=colors[i%colors.length];balloon.textContent=n;balloon.setAttribute('aria-label',`Balão número ${n}`);balloon.addEventListener('pointerdown',()=>{if(this.finished)return;this.attempts++;if(n===this.targetNumber){playSfx('pop');this.score++;this.audio.play(null,`Muito bem! Número ${n}`);balloon.remove();const scoreEl=document.getElementById('balloon-score');if(scoreEl)scoreEl.textContent=this.score;document.querySelectorAll('#balloon-dots span')[this.score-1]?.classList.add('done');setTimeout(()=>this.spawnRound(),450);}else{playSfx('retry');balloon.classList.add('animate-shake');this.audio.play(null,this.difficulty.feedback==='gentle'?'Vamos procurar juntos!':'Procure o número certo.');setTimeout(()=>balloon.classList.remove('animate-shake'),450);}});sky.appendChild(balloon);});}
  finish(){if(this.finished)return;this.finished=true;const score=Math.max(0,Math.min(this.difficulty.rounds,Math.round((this.difficulty.rounds/Math.max(this.difficulty.rounds,this.attempts))*this.difficulty.rounds)));this.audio.play(null,'Parabéns! Você completou os balões!');this.onComplete?.({score,rounds:this.difficulty.rounds,correct:this.score,attempts:this.attempts,maxScore:this.difficulty.rounds,completedRounds:this.difficulty.rounds,difficulty:this.level,ageId:this.ageId});}
}