import { playSfx } from '../engine/sfx.js';
import { resolveGameDifficulty, getGameChoiceCount } from '../../core/game-difficulty-policy.js';

export class PuzzleGame {
  constructor(containerId,audioEngine,onComplete,onBack){this.container=document.getElementById(containerId);this.audio=audioEngine;this.onComplete=onComplete;this.onBack=onBack;this.level=1;this.ageId='2-3y';}
  start(itemsData,level=this.level,options={}) {
    this.itemsData=itemsData;this.ageId=options.ageId||'2-3y';this.difficulty=resolveGameDifficulty(this.ageId,level,options);this.level=this.difficulty.level;this.finished=false;
    const count=Math.min(itemsData.length,getGameChoiceCount(this.difficulty,2,1,5));const puzzleItems=[...itemsData].sort(()=>Math.random()-0.5).slice(0,count);let matches=0,attempts=0;
    this.container.innerHTML=`<div class="w-full max-w-3xl flex flex-col items-center gap-5 my-auto"><div class="game-bar w-full"><button id="btn-back-game" class="game-back" aria-label="Voltar">⬅️</button><h2 class="game-title">🧩 Quebra-Cabeça</h2><div class="game-dots" id="puzzle-dots">${Array.from({length:count},()=>'<span></span>').join('')}</div></div><span class="sr-only">Peças: <span id="puzzle-count">0</span>/${count} · Tentativas: <span id="puzzle-attempts">0</span></span><div class="grid grid-cols-2 md:grid-cols-4 gap-4 w-full justify-items-center">${puzzleItems.map(item=>`<button data-target="${item.id}" class="puzzle-target w-28 h-28 md:w-32 md:h-32 bg-slate-100 rounded-3xl border-4 border-dashed border-slate-300 flex items-center justify-center text-6xl opacity-50 grayscale shadow-inner touch-target">${item.icon}</button>`).join('')}</div><div id="pieces-container" class="grid grid-cols-2 md:grid-cols-4 gap-4 w-full justify-items-center min-h-[130px]">${[...puzzleItems].sort(()=>Math.random()-0.5).map(item=>`<button data-piece="${item.id}" class="puzzle-piece w-28 h-28 md:w-32 md:h-32 bg-white rounded-3xl shadow-lg border-4 border-indigo-100 flex items-center justify-center text-6xl touch-target touch-none">${item.icon}</button>`).join('')}</div></div>`;
    document.getElementById('btn-back-game').addEventListener('click',()=>this.onBack());
    this.audio.prompt(null,'Arraste cada figura até a sombra igual.');
    this.container.querySelectorAll('.puzzle-piece').forEach(piece=>{let active=false;const originalParent=piece.parentElement;const moveAt=(x,y)=>{if(active){piece.style.left=`${x-56}px`;piece.style.top=`${y-56}px`;}};const onPointerDown=e=>{active=true;piece.style.transition='none';piece.style.position='fixed';piece.style.zIndex='1000';piece.setPointerCapture(e.pointerId);moveAt(e.clientX,e.clientY);};const onPointerUp=e=>{if(!active)return;active=false;attempts++;const attemptsEl=document.getElementById('puzzle-attempts');if(attemptsEl)attemptsEl.textContent=attempts;piece.style.display='none';const below=document.elementFromPoint(e.clientX,e.clientY);piece.style.display='flex';const target=below?.closest('.puzzle-target');if(target?.dataset.target===piece.dataset.piece){target.classList.remove('opacity-50','grayscale','border-dashed');target.classList.add('border-solid','border-emerald-400','bg-emerald-50');playSfx('success');piece.remove();matches++;document.getElementById('puzzle-count').textContent=matches;document.querySelectorAll('#puzzle-dots span')[matches-1]?.classList.add('done');const item=puzzleItems.find(i=>i.id===target.dataset.target);this.audio.play(item?.audio,`Muito bem! ${item?.label||''}`);if(matches===puzzleItems.length)setTimeout(()=>this.finish(puzzleItems.length,attempts),600);}else{playSfx('retry');piece.style.position='static';piece.style.zIndex='';piece.style.left='';piece.style.top='';piece.style.transition='transform 0.2s ease';originalParent?.appendChild(piece);this.audio.play(null,this.difficulty.feedback==='gentle'?'Vamos tentar de novo!':'Quase! Tente encaixar no lugar certo.');}};piece.addEventListener('pointerdown',onPointerDown);piece.addEventListener('pointermove',e=>moveAt(e.clientX,e.clientY));piece.addEventListener('pointerup',onPointerUp);piece.addEventListener('pointercancel',onPointerUp);});
  }
  finish(count,attempts){if(this.finished)return;this.finished=true;const score=Math.max(0,Math.min(count,count-Math.max(0,attempts-count)));this.audio.play(null,'Parabéns! Você completou o quebra-cabeça!');this.onComplete?.({score,rounds:count,correct:count,attempts,maxScore:count,completedRounds:count,difficulty:this.level,ageId:this.ageId});}
}